apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        role: app
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args: ["--cpu", "1"]
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m

